name: Compile ft_irc

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y make g++ valgrind
      - name: Make
        run: make

      - name: Run valgrind to check for memory leaks
        run: |
          valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./ircserver