name: Valgrind Memory Leak Test

on:
  push:
    branches:
      - main
      - fix_valgrind_test
  pull_request:
    branches:
      - main
      - fix_valgrind_test

jobs:
  memory-leak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Instalar dependências
        run: |
          sudo apt-get install -y valgrind

      - name: Conceder permissão de execução
        run: chmod +x test_valgrind.sh
        
      - name: Compilar o projeto
        run: make
        
      - name: Rodar teste de vazamento de memória com Valgrind
        run: ./.github/workflows/tests/test_valgrind.sh